config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'
  #  именованные маршруты для страниц Help, About и Contact
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  resources :vehicles do
    get   'edit-tags' => 'vehicles#edit_tags', as: 'edit_tags'
    patch 'update_tags' => 'vehicles#update_tags', as: 'update_tags'
    # put   'update_tags' => 'vehicles#update_tags', as: 'update-tags'
  end

  resources :tags
  get   'tags-settings' => 'tags#settings', as: 'tags_settings'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :vehicles
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_and_belongs_to_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  # Интересно что отсутствие этих методов, но наличие вьюх ничего не ломает !

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :load_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.order(:tag_name)
  end

  def settings
    @tags = Tag.order(:tag_name)
  end

  def show
  end

  def edit
  end

  def update
    if params[:customize]
      @tag.customized = true
    else
      @tag.customized = false
    end
    if @tag.update tag_params
    flash[:success] = "<b>Successfully updated !</b> <br> #{params.inspect}"
    redirect_to @tag
    # render :text => 'done'
    else
      render :edit
    end
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    unless params[:customize] # галочка customize при создании нового тега
      @tag.bg_color = nil
      @tag.font_color = nil
      @tag.border_color = nil
      @tag.customized = false
    else
      @tag.customized = true
    end

    if params[:tag][:tag_name] == 'new tag'
      flash[:success] = "<b>Wrong tag name !</b> <br> choose another tag name <br> #{params.inspect}"
      render :new
    else

      if @tag.save
        flash[:success] = "<b>Successfully created !</b> <br> #{params.inspect}"
        redirect_to @tag
        # render :index # как перенаправить на индекс???
      else
        render :new
      end
    end

  end

  def destroy
    if @tag.destroy
      flash[:success] = "<b>Successfully deleted !</b> <br> #{params.inspect}"
    end
    redirect_to tags_url
  end

  private

  def load_tag
    unless (@tag= Tag.find_by id: params[:id])
      # редирект 404 в случае отсутствия объекта
      render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
    end
  end

  def tag_params
    params.require(:tag).permit(:tag_name, :bg_color, :font_color, :border_color, :customize )
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  before_action :load_vehicle, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.order(:tag_name) # для draw_tag

    # если в строке запроса ?tag=1 ищем машины с таким тегом
    if (tag = params[:tag])
      @tag = tag
      vehicles_count = Tag.find(tag).vehicles.count
      vehicles_on_page = 9
      pages_count = vehicles_count / vehicles_on_page
      pages_count += 1 if vehicles_count % vehicles_on_page
      @pages_count = pages_count
      current_page = params[:page].to_i
      current_page = 1 if current_page == 0
      @current_page = current_page
      @vehicles = Tag.find(tag).vehicles.offset((current_page-1)*vehicles_on_page).limit(vehicles_on_page)
    else
      vehicles_count = Vehicle.count
      vehicles_on_page = 9
      pages_count = vehicles_count / vehicles_on_page
      pages_count += 1 if vehicles_count % vehicles_on_page
      @pages_count = pages_count
      current_page = params[:page].to_i
      current_page = 1 if current_page == 0
      @current_page = current_page
      @vehicles = Vehicle.offset((current_page-1)*vehicles_on_page).limit(vehicles_on_page)
    end

  end

  def show
  end

  def edit
    @tags = Tag.order(:tag_name)
  end

  def update
    if @vehicle.update vehicle_params
      # debugger
      # new_tag = Tag.find( params['vehicle']['tags'])
      # @vehicle.tags << new_tag
      # debugger
      flash[:success] = "<b>Successfully updated !</b> <br> #{params.inspect}"
      redirect_to @vehicle
      # render :text => 'done'
    else
      render :edit
    end
  end

  def destroy
  end

  def edit_tags
    # страница для добавления удаления тегов
    # debugger
    @vehicle= Vehicle.find_by id: params[:vehicle_id]
    @tags = Tag.order(:tag_name)
  end

  def update_tags
    # метод который производит изменение списка тегов для машины
    # debugger
    # массивы id-шников для добавлени, изменения, удаления. Если не пришло, то инициализирем пустым массивом
    params['update_tags'].nil? ? tags_to_update = [] : tags_to_update = params['update_tags'].map! {|t| t.to_i}
    # это было раньше (старая версия)
    params['add_tags'].nil? ? tags_to_add = [] : tags_to_add = params['add_tags'].map! {|t| t.to_i}
    params['dell_tags'].nil? ? tags_to_dell = [] : tags_to_dell = params['dell_tags'].map! {|t| t.to_i}

    @vehicle= Vehicle.find_by id: params[:vehicle_id]
    vehicle_tag_ids = @vehicle.tags.map {|t| t.id} # достать все id привязаных тегов и положить в массив
    # debugger

    unless tags_to_update.empty? # если нам прислали id-шники для обновления
      # перебераем все, и если еще такие привязаны - удаляем, не привязаны - добавляем,
      all_tags = Tag.all.map { |t| t.id }
      vehicle_tags = @vehicle.tags.map { |t| t.id }
      # debugger
      # наполняем массывы тегов для удаления и добавлени
      tags_to_update.each { |tag| tags_to_add << tag unless vehicle_tags.include? tag }
      vehicle_tags.each { |tag| tags_to_dell << tag unless tags_to_update.include? tag }
      # debugger
      # нижеследующие блоки проделают дяльнейную работу
    end
    # debugger
    # старая версия
    unless tags_to_add.empty? # если нам прислали id-шники для добавления
      # перебераем все, и если еще такие не привязаны - добавляем
      tags_to_add.each { |t| (@vehicle.tags << Tag.find(t)) unless vehicle_tag_ids.include? t }
    end
    # debugger
    # старая версия
    unless tags_to_dell.empty?  # если нам прислали id-шники для удаленя
      # удаляем те которые есть
      tags_to_dell.each { |t| @vehicle.tags.delete Tag.find(t) if vehicle_tag_ids.include? t }
    end

    redirect_to @vehicle
    # render :text => 'ok'
  end


  private

  def load_vehicle
    unless (@vehicle= Vehicle.find_by id: params[:id])
      # редирект 404 в случае отсутствия объекта
      render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
    end
  end

  def vehicle_params
    params.require(:vehicle).permit(:model, :year, :description )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper

  # отрисовка одного тега
  def draw_tag(tag, path=vehicles_path) # path для отладки в консоли app.vehicles_path
    output = "<a href='#{path}?tag=#{tag.id}'><span class='tag'" # label label-default
    output = "<a href='#{path}/#{tag.id}'><span class='tag'" if path == tags_path # костыль для tags/index.html.erb
    # кастомизация
    if tag.customized
      output += " style='"
      output += "background-color: #{tag.bg_color}; " if tag.bg_color
      output += "color: #{tag.font_color}; " if tag.font_color
      output += "border-color: #{tag.border_color || tag.bg_color}; " # такой же цвет, если не установлен особый
      output += "'"
    end
    output += ">#{tag.tag_name}</span></a>"
    output.html_safe
  end

  # вывод всех тегов
  def draw_tags(tags, path=vehicles_path)
    output = ''
    tags.each do |t|
        output += draw_tag t, path
        output += ' '
      end
    output.html_safe
  end
  # для отладки в консоли   helper.draw_tags Tag.all, app.vehicles_path

end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Home', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to vehicles_path, "class" => "nav-link" do %>
          Vehicles
          <span class="sr-only">(current)</span>
        <%end %>
      </li>
      <li class="nav-item">
        <%= link_to 'Tag list', tags_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Tags settings', tags_settings_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
<!--  <title>Catalog</title>-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=render 'layouts/header' unless current_page? root_path %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message.html_safe %></div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, 'About' %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contactpage</a>.
</p>

app/views/static_pages/help.html.erb
<% provide :title, 'Help' %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide :title, 'Home' %>

<div class="center jumbotron">
  <h1 class="text-center">Welcome to Car catalog application</h1>
  <h2 class="text-center">This is the home page</h2>
</div>
 <div class="text-center">
  <%= link_to "See all cars now!", vehicles_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/tags/_tags.html.erb
<%# default_color = '#999999' %>
<%# @tags.each do |tag| %>
    <%#= draw_tag tag %>
<%# end %>

<%#
    ЭТО партиал
СДЕЛАТЬ хелпер для тегов

    УЖЕ СДЕЛАЛ !!!

сделать цвета для фона, шрифта, бардюра
доступными везде
%>

app/views/tags/destroy.html.erb
destroyed

app/views/tags/edit.html.erb
<h1>Edit Tag <%=@tag.tag_name %></h1>
<%# if @tag.customized == false %>
  <%# @tag.bg_color = '#999999'; @tag.font_color = '#000000'; @tag.border_color = '#999999' %>
<%# end %>
<%= form_for @tag do |f| %>

  <%= f.label 'tag name' %>
  <%= f.text_field :tag_name %>
  <br><br>
  <%= f.label 'tag color' %>
  <%= f.color_field :bg_color %>

  <br><br>
  <%= f.label 'font color' %>
  <%= f.color_field :font_color %>

  <br><br>
  <%= f.label 'border color' %>
  <%= f.color_field :border_color %>

  <br><br>
  <%= f.label 'customized' %>
  <%= check_box_tag 'customize', 1, @tag.customized %>

  <br><br>
  <%= f.submit 'change' %>
<%end %>

app/views/tags/index.html.erb
<h1>Tag list</h1>
<%= draw_tags @tags %>
<%#, tags_path используется путь по умолчанию и параметров по умолчанию draw_tag(tag, path=vehicles_path)%>

app/views/tags/new.html.erb
<h1>create new tag</h1>
<% @tag.tag_name = 'new tag'; @tag.bg_color = '#999999'; @tag.font_color = '#000000'; @tag.border_color = '#999999' %>
  <%= form_for @tag do |f| %>
    <%#= render 'shared/error_messages' %>
  <%= f.label :name %>
  <%= f.text_field :tag_name %>

  <br><br>
  <%= f.label 'tag color' %>
  <%= f.color_field :bg_color %>

  <br><br>
  <%= f.label 'font color' %>
  <%= f.color_field :font_color %>

  <br><br>
  <%= f.label 'border color' %>
  <%= f.color_field :border_color %>

  <% cat = ['color','size'] %>
  <br><br>
  <%= f.label 'category' %>
  <%= select(:product, :group_id, cat.collect {|t| [ "#{t}" , t ] }, {include_blank: 'no category'} )%>

  <br><br>
  <%= f.label 'customized' %>
  <%= check_box_tag 'customize', 1 %>

  <%= f.submit 'create' %>

  <% end %>

app/views/tags/settings.html.erb
<h1>Tags settings</h1>
<%= draw_tags @tags, tags_path %>
<p>
  <button><%= link_to 'add new tag', new_tag_path %></button>
</p>

app/views/tags/show.html.erb
<% default_color = '#999999' %>
<h1>Tag information</h1>
<p>
  <%= draw_tag @tag %>
  <button><%= link_to 'edit', edit_tag_path(@tag)%></button>
  <button><%= link_to 'delete', tag_path(@tag), method: :delete %></button>
  <button><%= link_to 'Back', :back %></button>
  <button><%= link_to 'all tags', tags_path %></button>
</p>

app/views/vehicles/_pager.html.erb
<%if @tag %>
  <% tag = "&tag=#{@tag}" %>
<%else %>
  <% tag ='' %>
<%end %>
<div class="d-flex justify-content-around">
  <div class="p-2 bd-highlight"><%# Previous Page %>
      <% if @current_page > 1 %>
        <%= link_to vehicles_path + "?page=#{@current_page-1}#{tag}", {:"aria-label" => "Previous", :"class" => "btn btn-outline-secondary", :"style" => "width: 8em;"  } do %>
          <span aria-hidden="true">Previous</span>
        <%end %>
      <%else %>
        <div class="btn btn-outline-secondary disabled" style="width: 8em;">
          <span aria-hidden="true">Previous</span>
        </div>
      <%end %>
  </div>

  <div class="p-2 bd-highlight"><%# Next Page %>
      <% if @current_page < @pages_count %>
        <%= link_to vehicles_path + "?page=#{@current_page+1}#{tag}", {:"aria-label" => "Next", :"class" => "btn btn-outline-secondary", :"style" => "width: 8em;" } do %>
          <span aria-hidden="true">Next</span>
        <%end %>
      <%else %>
      <div class="btn btn-outline-secondary disabled" style="width: 8em;">
        <span aria-hidden="true">Next</span>
      </div>
      <%end %>
  </div>
</div>

app/views/vehicles/_paginator.html.erb
<%if @tag %>
  <% tag = "&tag=#{@tag}" %>
<%else %>
  <% tag ='' %>
<%end %>
<nav aria-label="Page navigation">
  <ul class="pagination  pagination-sm">
    <li class="page-item"><%# -10 Page %>
        <%= link_to vehicles_path + "?page=#{@current_page - 10 > 0 ? @current_page -10 : 1}#{tag}", {:"aria-label" => "Previous", :"class" => "page-link" } do %>
          <span aria-hidden="true">&laquo;</span>
        <%end %>
    </li>
    <li class="page-item"><%# Previous Page %>
      <% if @current_page > 1 %>
        <%= link_to vehicles_path + "?page=#{@current_page-1}#{tag}", {:"aria-label" => "Previous", :"class" => "page-link" } do %>
          <span aria-hidden="true">&lsaquo;</span>
        <%end %>
      <%else %>
        <%= link_to "#", {:"aria-label" => "", :"class" => "page-link" } do %>
          <span aria-hidden="true">&lsaquo;</span>
        <%end %>
      <%end %>
    </li>
    <%# Smart Pager %>
    <%
      numbers = []
      if @pages_count <= 8
        numbers = 1..@pages_count
      else
        if @current_page <= 3
          numbers += (1..6).to_a
          numbers << '&hellip;'
          numbers  << @pages_count
        else
          if @current_page < @pages_count - 7
            p_start = @current_page - 2
            p_end = @current_page + 3
            numbers += (p_start..p_end).to_a
            numbers << '&hellip;'
            numbers  << @pages_count
          else
            p_start = @pages_count - 7
            p_end = @pages_count
            numbers += (p_start..p_end).to_a
          end
        end
      end
      # debugger
     %>
    <% numbers.each_with_index do |n,p| %><%# TODO выводить только 5 номеров страниц, затем троеточие и последнюю %>
      <li class="page-item <%='active' if n == @current_page %>" >
        <%if n.to_i > 0 %>
        <%= link_to "#{n}".html_safe, vehicles_path + "?page=#{n}#{tag}" , :"class" => "page-link"%>
        <%else %>
          <span class="page-link" aria-hidden="true">&hellip;</span>
        <%end %>
      </li>
    <% end %>
    <li class="page-item"><%# Next Page %>
      <% if @current_page < @pages_count %>
      <%= link_to vehicles_path + "?page=#{@current_page+1}#{tag}", {:"aria-label" => "Next", :"class" => "page-link" } do %>
        <span aria-hidden="true">&rsaquo;</span>
      <%end %>
      <%else %>
        <%= link_to "#", {:"aria-label" => "", :"class" => "page-link" } do %>
            <span aria-hidden="true">&rsaquo;</span>
        <%end %>
      <%end %>
    </li>
    <li class="page-item"><%# +10 Page %>
      <%= link_to vehicles_path + "?page=#{@current_page + 10 <= @pages_count ? @current_page + 10 : @pages_count }#{tag}", {:"aria-label" => "Previous", :"class" => "page-link" } do %>
        <span aria-hidden="true">&raquo;</span>
      <%end %>
    </li>
  </ul>
</nav>

app/views/vehicles/edit.html.erb
<h2>Edit vehicle information</h2>
<p>
  <%= draw_tags @vehicle.tags %>
</p>
<div class="row row-cols-1 row-cols-md-2">
  <div class="col mb-4">
<div class="card" style="width: 100%; max-width: 32rem">
  <img src="<%= "/#{@vehicle.img_url}" %>" class="card-img-top" alt="car image">
  <div class="card-body">
    <h5 class="card-title">Vehicle details</h5>
    <p class="card-text">
      description: <%= @vehicle.description  || 'not defined' %>
    </p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">model: <%= @vehicle.model || 'not defined' %></li>
    <li class="list-group-item">year: <%= @vehicle.year  || 'not defined' %></li>
  </ul>
</div>
  </div>
  <div class="col mb-4">
<%= form_for @vehicle do |f| %>
  <div class="form-group">
    <%= f.label 'model' %>
    <%= f.text_field :model, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'year' %>
    <%= f.text_field :year, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'description' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%=f.submit 'Change', class: "btn btn-danger" %>
  <%=link_to 'Edit tags', vehicle_edit_tags_path(@vehicle), class: "btn btn-warning" %>
  <%=link_to 'Back', :back, class: "btn btn-info" %>
  </div>
<%end %>
  </div>
</div>

app/views/vehicles/edit_tags.html.erb
  <h2>Vehicle tags - add and remove</h2>
  <%= draw_tags @vehicle.tags%> <%# теги конкретной машины %>
  <div class="row row-cols-1 row-cols-md-2">
    <div class="col mb-4">
      <div class="card" style="width: 100%; max-width: 32rem">
        <img src="<%= "/#{@vehicle.img_url}" %>" class="card-img-top" alt="car image">
        <div class="card-body">
          <h5 class="card-title">Vehicle details</h5>
          <p class="card-text">
            description: <%= @vehicle.description  || 'not defined' %>
          </p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">model: <%= @vehicle.model || 'not defined' %></li>
          <li class="list-group-item">year: <%= @vehicle.year  || 'not defined' %></li>
        </ul>
      </div>
    </div>
    <div class="col mb-4">
      <% vehicle_tags_ids = @vehicle.tags.map {|t| t.id} # id-шники тегов машины %>
      <%= form_for :tag, url: vehicle_update_tags_path, method: :patch, html: { class: "bla-bla", id: "bla-bla" } do |f|  %>

        <%# рисуем теги с чекбоксами %>
        <% @tags.each do |tag| %>
          <div class="tag-checkbox" style="background-color: <%= tag.bg_color %>" >
            <span class="tag" style="background-color: <%= tag.bg_color %>; color: <%= tag.font_color %>" ><%= tag.tag_name %></span>
            <%= check_box_tag "update_tags[]", tag.id, vehicle_tags_ids.include?(tag.id) %><%# checked для тегов которые уже есть %>
          </div>
        <% end %>

        <br style="clear: both"><%# отмена флоата%>

        <%= f.submit 'Update tags', class: "btn btn-danger" %>
      <%end %>
      <%=link_to 'Back', :back, class: "btn btn-info" %>
    </div>
  </div>

app/views/vehicles/index.html.erb
<%= render 'vehicles/paginator' %>

<div class="row row-cols-1 row-cols-md-3">
  <%  @vehicles.each do |vehicle| %>
    <div class="col mb-4">
      <div class="card">
      <img src="<%= vehicle.img_url %>" class="card-img-top" alt="car image">
      <div class="card-body">
        <h5 class="card-title">model: <%= vehicle.model  || 'not defined' %></h5>
        <p class="card-text">
          <%= draw_tags vehicle.tags %>
        </p>
        <p class="card-text">
          <%=link_to 'Details', vehicle_path(vehicle.id), class: "btn btn-info" %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

<%= render 'vehicles/pager' %>

app/views/vehicles/old_edit_tags.html.erb
<div class="container">
  <h2>Vehicle tags - add and remove</h2>
  <% default_color = '#999999' %>
  <% vehicle_tags = @vehicle.tags # теги конкретной машины %>
  <% vehicle_tags.each do |tag| %>
    <a href="<%= tag_path tag.id %>">
      <span class="tag" style="background-color: <%= tag.bg_color  || default_color %>" ><%= tag.tag_name %></span>
    </a>
  <% end %>
  <br><br>
  <div>
    <img class='big-image' src="<%= "/#{@vehicle.img_url}" %>" alt=''>
  </div>
</div>

<%# ЗДЕСЬ ТРИ ФОРМЫ: изменеие, добавление, удаление

<% vehicle_tags_ids = @vehicle.tags.map {|t| t.id} # id-шники тегов машины %>

<%= form_for :tag, url: vehicle_update_tags_path, method: :patch, html: { class: "bla-bla", id: "bla-bla" } do |f|  %>

  <% @tags.each do |tag| %>
    <div class="tag-checkbox" style="background-color: <%= tag.bg_color  || default_color %>" >
      <span class="tag"><%= tag.tag_name %></span>
      <%#debugger %>

      <%= check_box_tag "update_tags[]", tag.id, vehicle_tags_ids.include?(tag.id) %><%# checked для тегов которые уже есть %>

    </div>

  <% end %>
  <br style="clear: both">
  <%= f.submit 'update tags' %>

<%end %>


<%= form_for :tag, url: vehicle_update_tags_path, method: :patch, html: { class: "bla-bla", id: "bla-bla" } do |f|  %>

  <% @tags.each do |tag| %>
    <div class="tag-checkbox" style="background-color: <%= tag.bg_color  || default_color %>" >
    <span class="tag"><%= tag.tag_name %></span>
    <%= check_box_tag "add_tags[]", tag.id %>
    </div>
  <%end %>
<!--<div class="clear-float"></div>-->
  <br style="clear: both">
  <%= f.submit 'add tags' %>

<%end %>


<%= form_for :tag, url: vehicle_update_tags_path, method: :patch, html: { class: "bla-bla", id: "bla-bla" } do |f|  %>

  <% @tags.each do |tag| %>
    <div class="tag-checkbox" style="background-color: <%= tag.bg_color  || default_color %>" >
      <span class="tag"><%= tag.tag_name %></span>
      <%= check_box_tag "dell_tags[]", tag.id %>
    </div>
  <%end %>
  <!--<div class="clear-float"></div>-->
  <br style="clear: both">
  <%= f.submit 'delete tags' %>

<%end %>









<%#= f.label 'add new tag' %>
<%#= select(:vehicle, :tags, @tags.collect {|t| [ t.tag_name , t.id ] }, {include_blank: 'no group' } , multiple: true, size: 10 ) %>

app/views/vehicles/show.html.erb
  <h2>Vehicle details</h2>

  <div class="card" style="width: 100%; max-width: 32rem">
    <img src="<%= "/#{@vehicle.img_url}" %>" class="card-img-top" alt="car image">
    <div class="card-body">
      <h5 class="card-title">Vehicle details</h5>
      <p>
        <%= draw_tags @vehicle.tags %>
      </p>
      <p class="card-text">
        description: <%= @vehicle.description  || 'not defined' %>
      </p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">model: <%= @vehicle.model || 'not defined' %></li>
      <li class="list-group-item">year: <%= @vehicle.year  || 'not defined' %></li>
    </ul>
    <div class="card-body">
      <%=link_to 'Edit', edit_vehicle_path(@vehicle), class: "btn btn-warning" %>
      <%=link_to 'Edit tags', vehicle_edit_tags_path(@vehicle), class: "btn btn-warning" %>
      <%=link_to 'Back', :back, class: "btn btn-info" %>
    </div>
  </div>